#!/usr/bin/env python3

import requests
import json
import sys

if (sys.argv[1] == ''):
    message = 'ok'
else:
    message = sys.argv[1]
data = {'text': message}
headers = 'Content-type: application/json'
url = '' #url hook for slack https://hooks.slack.com/services/000000/00000000/0000000
req = requests.post(url, json.dumps(data), headers)

if req.ok:
    print('Message Send')
    print(req.content.decode('utf-8'))
else:
    print('Message Send False')
    print(req.content.decode('utf-8'))
